services:
  qr-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr-service
    volumes:
      - .:/app
    ports:
      - "8004:8000"
    depends_on:
      - db
    environment:
      - DB_URL=postgresql+asyncpg://postgres:postgres@qr-db:5432/qr_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    networks:
      - attendance_net

  db:
    image: postgres:15
    container_name: qr-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qr_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - attendance_net

volumes:
  postgres_data:

networks:
  attendance_net:
    external: true